[12] added robot status refresh with button
jurczewski/raptors pull request #10
Opened 2020-05-25 13:33 UTC by shreq

2020-05-25 14:01 UTC, jurczewski commented
![image](https://user-images.githubusercontent.com/24575781/82819469-b82af380-9ea0-11ea-9843-3a121ff7baac.png)

![image](https://user-images.githubusercontent.com/24575781/82819538-d133a480-9ea0-11ea-8966-cc13ae131026.png)

Table width differ when field "position" is too long.

2020-05-26 10:30 UTC, Pawci0 requested changes

2020-05-26 10:30 UTC, Pawci0 commented on angularclient/src/app/components/robotpanel-new/robot-details-new/robot-details-new.component.html
> +      <button class="material-icons refresh" (click)="callParent()">refresh</button>
```suggestion
      <button class="material-icons refresh" (click)="refresh()">refresh</button>
```

2020-05-26 10:47 UTC, Pawci0 approved these changes

2020-05-26 10:48 UTC, Pawci0 commented
lgtm

2020-05-26 10:50 UTC, merged