Model and logs tables side-by-side
jurczewski/raptors pull request #19
Opened 2020-06-12 10:55 UTC by jurczewski

2020-06-12 18:04 UTC, Pawci0 requested changes
please position the tables more to the left

![image](https://user-images.githubusercontent.com/26577746/84533181-e48ba000-ace7-11ea-87ab-8a1cc1c401cc.png)

2020-06-13 11:09 UTC, shreq approved these changes

2020-06-13 11:43 UTC, jurczewski commented
> please position the tables more to the left
> 
> ![image](https://user-images.githubusercontent.com/26577746/84533181-e48ba000-ace7-11ea-87ab-8a1cc1c401cc.png)

Done.

2020-06-13 14:51 UTC, Pawci0 approved these changes
lgtm

2020-06-13 15:09 UTC, merged